### ISSUE TITLE
Tarea uno

### ISSUE THREAD

**Issue by alegriajr11** [alegriajr11/ejemplo-gustavo#1]
Se debe realizar x funcionalidad para el modulo tobby en donde se requiere que este no coma tanto

- [ ] Item unoi
- [x] Item dos

![Image](https://github.com/user-attachments/assets/0fb91b84-997a-4fba-8042-d7773c1c1e99)

Se espera que se cumpla con lo anterior mencionado

**Comment by gustavo177** [comment]
151515
